import type { SampleInvoice } from "@/components/dropzone";

/**
 * The handful of sample invoices surfaced as "try an example" buttons on the
 * landing page — a subset of the full eval corpus, generated by `pnpm eval:gen`
 * (PDF → public/samples/<id>.pdf, first-page thumbnail →
 * public/samples/previews/<id>.png).
 */
const LANDING: ReadonlyArray<{ id: string; label: string }> = [
  { id: "clean-acme", label: "Clean invoice" },
  { id: "multicurrency-eur", label: "Multi-currency (EUR)" },
  { id: "math-error", label: "Has a math error" },
  { id: "non-english-de", label: "Non-English (German)" },
  { id: "non-english-he", label: "Hebrew (RTL)" },
];

export const LANDING_SAMPLES: SampleInvoice[] = LANDING.map(({ id, label }) => ({
  id,
  label,
  file: `/samples/${id}.pdf`,
  preview: `/samples/previews/${id}.png`,
}));
