import type { SampleInvoice } from "@/components/dropzone";

/**
 * The handful of sample invoices surfaced as "try an example" buttons on the
 * landing page. These point at PDFs in /public/samples, which are generated by
 * `pnpm eval:gen` (a subset of the full eval corpus). Keep the `file` paths in
 * sync with eval/samples/<id>.pdf → copied to public/samples/<id>.pdf.
 */
export const LANDING_SAMPLES: SampleInvoice[] = [
  { id: "clean-acme", label: "Clean invoice", file: "/samples/clean-acme.pdf" },
  {
    id: "multicurrency-eur",
    label: "Multi-currency (EUR)",
    file: "/samples/multicurrency-eur.pdf",
  },
  {
    id: "math-error",
    label: "Has a math error",
    file: "/samples/math-error.pdf",
  },
  {
    id: "non-english-de",
    label: "Non-English (German)",
    file: "/samples/non-english-de.pdf",
  },
  {
    id: "non-english-he",
    label: "Hebrew (RTL)",
    file: "/samples/non-english-he.pdf",
  },
];
